services:
  mongodb:
    image: mongo:7
    container_name: pechenka-mongodb
    ports:
      - "27018:27017"
    volumes:
      - pechenka_mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pechenka
    restart: unless-stopped

volumes:
  pechenka_mongodb_data:
